### ISSUE TITLE
Inflect 설정 옵션 추가 요청

### ISSUE THREAD

**Issue by mu0gum** [gritmind/python-nori#1]
안녕하세요. pynori를 사용하던 중에 추가되었으면 하는 기능이 있어 이슈를 등록하게 되었습니다.
pynori 0.1.1 기준으로 형태소 분석을 하게 되면, 기본적으로 Inflect 처리가 되어 결과가 나옵니다.
요청 드리는 기능은 Compound 처럼 옵션별로 원하는 결과를 리턴하는 기능입니다.

예를 들어,

가까운 = 가깝 + ㄴ 이 있으면

* 가까운 가깝 ㄴ
* 가까운
* 가깝 ㄴ

이런식으로 결과를 받아볼 수 있는 기능을 요청 드립니다.
이런 기능을 요청하게 된 이유는 BERT에서 토크나이징을 할 때, 형태소 분석 없이 vocab만을 만들어 사용하려고 합니다.

vocab을 만들기 위해 pynori로 형태소 분석을 돌린 후, 나온 형태소의 원형을 사용하려고 합니다.
"가깝ㄴ" 대신에 "가까운" 을 사전에 등록하고 싶습니다.
해당 기능이 추가된다면

1. 옵션 다양화
2. 자연어 처리의 목적이 Inflect 처리 여부와는 크게 연관되지 않는 케이스에 대해 형태소 분석 작업 경량화

등에 이점이 있을 것으로 판단됩니다. 기능 추가에 대해 고려 부탁 드립니다.
끝으로 pynori와 같은 좋은 형태소 분석기를 만들어 주셔서 감사합니다.

**Comment by gritmind** [comment]
@mu0gum 안녕하세요
먼저 pynori에 관심주셔서 감사드립니다.

요청해주신 것처럼 inflect 단어들도 일반 복합명사와 같이
원형어, 서브단어의 출력을 제어하기 위한 옵션을 추가했습니다.

옵션은 infl_decompound_mode 이고, 사용법은 기존 decompound_mode와 동일합니다.
유닛테스트를 실시하여 정상 동작 여부를 확인했습니다.

위의 내용이 반영된 버전으로 새롭게 pynori 0.1.2 를 release 했습니다.
혹시 이슈가 발생하면 알려주세요.
