### ISSUE TITLE
0.2.1 버전 오류 문의드립니다~

### ISSUE THREAD

**Issue by cheesama** [gritmind/python-nori#2]
안녕하세요 만들어주시는 해당 라이브러리 잘 사용하고 있습니다. 감사합니다

다름이 아니라 0.2.1 최신 버전에서 아래와 같은 오류가 나는데요, 확인 가능할까요?ㅎㅎ

감사합니다~

  File "/usr/local/lib/python3.6/dist-packages/pynori/post_processing.py", line 62, in relax_long_unk
    front_string = long_unknown_token[:idx]
UnboundLocalError: local variable 'idx' referenced before assignment

**Comment by gritmind** [comment]
안녕하세요 해당 버그 수정 완료했습니다. (참고 - https://github.com/gritmind/python-nori/commit/30464d13eb9413fd11d5f39fa2b80d93f6e37cab)
pynori를 사용해주셔서 감사드립니다.
조금이라도 문제점이 있으면 언제든지 문의주세요!
감사합니다.
